import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/about',
          '/features',
          '/modules',
          '/pricing',
          '/why-us',
          '/faq',
          '/testimonials',
          '/guides/',
          '/contact',
          '/privacy-policy',
          '/terms',
          '/refund-policy',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/superadmin/',
          '/teacher/',
          '/portal/',
          '/login/',
          '/sign-in/',
          '/sign-up/',
          '/change-password/',
          '/dev/',
          '/unauthorized',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/about',
          '/features',
          '/modules',
          '/pricing',
          '/why-us',
          '/faq',
          '/testimonials',
          '/guides/',
          '/contact',
          '/privacy-policy',
          '/terms',
          '/refund-policy',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/superadmin/',
          '/teacher/',
          '/portal/',
          '/login/',
          '/sign-in/',
          '/sign-up/',
          '/change-password/',
          '/dev/',
          '/unauthorized',
        ],
      },
    ],
    sitemap: 'https://alphaeduhub.in/sitemap.xml',
    host: 'https://alphaeduhub.in',
  };
}
